#!/usr/bin/env bash

# Bidirectional HOMER motif enrichment — mm10, summit-centered (200bp)
#
# Purpose:
#   Run 4 HOMER findMotifsGenome.pl analyses on summit-centered 200bp
#   windows, comparing mouse-specific vs conserved peaks in BOTH directions.
#
# Why summit-centering?
#   Raw ATAC peaks vary in length (hundreds to thousands of bp). By centering
#   all peaks on their summit (the position of maximum signal) and trimming
#   to a fixed 200bp window, we eliminate size bias and focus motif discovery
#   on the most biologically relevant region.
#
# Input files (generated by build_centered_beds.sh):
#   mousespecific_enhancers.summit200.bed      (mm10, native mouse peaks)
#   mousespecific_promoters.summit200.bed      (mm10, native mouse peaks)
#   mouse_conserved_enhancers.summit200.bed    (mm10, native mouse peaks)
#   mouse_conserved_promoters.summit200.bed    (mm10, native mouse peaks)
#
# 4 comparisons:
#   mousespecific_enhancers (target) vs mouse_conserved_enhancers (bg)
#   mousespecific_promoters (target) vs mouse_conserved_promoters (bg)
#   mouse_conserved_enhancers (target) vs mousespecific_enhancers (bg)
#   mouse_conserved_promoters (target) vs mousespecific_promoters (bg)
#
# What HOMER does internally (findMotifsGenome.pl):
#   1. Reads the target BED → extracts DNA sequences from the mm10 genome
#   2. Reads the background BED → extracts DNA sequences from mm10
#   3. Known motif enrichment: scans both sets against a database of ~470
#      known vertebrate motifs, computes enrichment (binomial test) of each
#      motif in target vs background
#   4. De novo motif discovery: searches for novel over-represented sequence
#      patterns in target relative to background using the HOMER2 algorithm
#   5. Outputs: knownResults.txt/html (known), homerMotifs.all.motifs (de novo)
#
# Bash strict mode:
#   -e: exit immediately on any command failure
#   -u: treat unset variables as errors
#   -o pipefail: pipeline returns the exit code of the first failing command

set -euo pipefail

# Environment setup


# Resolve this script's directory so all relative paths (input BEDs, HOMER)
# work the same regardless of where the user invokes the script from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# HOMER installation is one level up: task5/homer/
HOMER_HOME="$SCRIPT_DIR/../homer"
FIND_MOTIFS="$HOMER_HOME/bin/findMotifsGenome.pl"

# Add HOMER bin/ to PATH so that findMotifsGenome.pl can locate its
# internal helpers (bed2pos.pl, homer2, findKnownMotifs.pl, etc.).
export PATH="$HOMER_HOME/bin:$PATH"


# Preflight checks


# 1) Verify the main HOMER executable exists and is executable.
if [[ ! -x "$FIND_MOTIFS" ]]; then
  echo "ERROR: findMotifsGenome.pl not found at: $FIND_MOTIFS"
  exit 1
fi

# 2) Verify every internal helper that findMotifsGenome.pl calls at runtime.
#    If any is missing, HOMER will silently fail or produce empty results.
for tool in bed2pos.pl checkPeakFile.pl cleanUpPeakFile.pl mergePeaks homerTools findKnownMotifs.pl homer2 compareMotifs.pl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: required HOMER helper not found in PATH: $tool"
    exit 1
  fi
done

# Analysis parameters


GENOME="mm10"    # Reference genome for sequence extraction (must be installed)
THREADS=8        # Parallel threads for motif scanning
LENS="8,10,12"   # Motif widths to search: 8bp, 10bp, and 12bp

# Input file validation

# check_file: abort immediately if a required input is missing or empty (0 bytes).
# Uses -s (exists AND size > 0) rather than -f (exists only).
check_file() {
  local f="$1"
  if [[ ! -s "$f" ]]; then
    echo "ERROR: missing or empty file: $f"
    exit 1
  fi
}

# Mouse-specific peaks (summit-centered 200bp, from native mouse ATAC data)
check_file "mousespecific_enhancers.summit200.bed"
check_file "mousespecific_promoters.summit200.bed"

# Conserved peaks, mouse side (summit-centered 200bp, from native mouse ATAC data)
check_file "mouse_conserved_enhancers.summit200.bed"
check_file "mouse_conserved_promoters.summit200.bed"

# HOMER runner function

# run_cmd <target_bed> <output_dir> <background_bed> <step_label>
#
# Workflow inside this function:
#   1. Log the start time and comparison being run
#   2. rm -rf the output directory to prevent stale results from a prior run
#   3. Call findMotifsGenome.pl:
#        - Reads target_bed → extracts sequences from $GENOME
#        - Reads bg_bed → extracts background sequences from $GENOME
#        - Runs known motif enrichment (binomial test, ~470 vertebrate motifs)
#        - Runs de novo motif discovery (HOMER2 algorithm, 25 iterations per length)
#        - Writes results to output_dir/
#   4. Post-run validation: check that knownResults.txt and .html exist and
#      are non-empty; abort if HOMER silently failed
#   5. Log completion time
run_cmd() {
  local target_bed="$1"   # BED file of regions to test for motif enrichment
  local out_dir="$2"      # Directory where HOMER writes all output files
  local bg_bed="$3"       # BED file of background/control regions
  local step_label="$4"   # Human-readable label for logging (e.g. "1/4")

  echo "[$(date '+%F %T')] START [$step_label]: $target_bed vs $bg_bed -> $out_dir"

  # Clean slate: remove any leftover output from a previous interrupted run
  rm -rf "$out_dir"

  # Core HOMER command:
  #   -size given   : use each BED interval's actual coordinates (200bp here)
  #   -bg <file>    : user-supplied background sequences (not HOMER default)
  #   -p <threads>  : number of CPUs for parallel motif scanning
  #   -len <widths> : motif lengths to search (comma-separated)
  "$FIND_MOTIFS" "$target_bed" "$GENOME" "$out_dir" \
    -size given \
    -bg "$bg_bed" \
    -p "$THREADS" \
    -len "$LENS"

  # Post-run validation: HOMER can exit 0 but produce no results if
  # internal helpers are missing or genome data is incomplete.
  if [[ ! -s "$out_dir/knownResults.txt" ]]; then
    echo "ERROR [$step_label]: missing or empty $out_dir/knownResults.txt"
    exit 1
  fi
  if [[ ! -s "$out_dir/knownResults.html" ]]; then
    echo "ERROR [$step_label]: missing or empty $out_dir/knownResults.html"
    exit 1
  fi

  echo "[$(date '+%F %T')] DONE  [$step_label]: $out_dir"
}

# Run 4 comparisons

# Forward direction: what motifs are enriched in mouse-specific vs conserved?
# → Finds motifs that are over-represented in species-specific regulatory regions
run_cmd "mousespecific_enhancers.summit200.bed" "out_mouseSpecEnh_centered_bidir"  "mouse_conserved_enhancers.summit200.bed"  "1/4"
run_cmd "mousespecific_promoters.summit200.bed" "out_mouseSpecProm_centered_bidir" "mouse_conserved_promoters.summit200.bed"  "2/4"

# Reversed direction: what motifs are enriched in conserved vs mouse-specific?
# → Finds motifs that are over-represented in shared/conserved regulatory regions
run_cmd "mouse_conserved_enhancers.summit200.bed" "out_conservedEnh_centered_vs_mouseSpec"  "mousespecific_enhancers.summit200.bed" "3/4"
run_cmd "mouse_conserved_promoters.summit200.bed" "out_conservedProm_centered_vs_mouseSpec" "mousespecific_promoters.summit200.bed" "4/4"

echo "All four mm10 summit-centered bidirectional HOMER analyses completed successfully."

# Reference
# LLM was used for debugging
# [1] OpenAI, "GPT-5.4 Thinking System Card," Mar. 5, 2026. Accessed: Apr. 13, 2026.
